# Generated by Django 4.2 on 2023-04-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.IntegerField(choices=[(1, 'шт.'), (2, 'кг.'), (3, 'лит.')], verbose_name='единица измерения'),
        ),
    ]
