# Generated by Django 4.2 on 2023-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(choices=[('штук', 'шт.'), ('килограмм', 'кг.'), ('литров', 'лит.')], max_length=15, verbose_name='единица измерения'),
        ),
    ]
