# Generated by Django 4.2 on 2023-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(choices=[('шт.', 'штук'), ('кг.', 'килограмм'), ('лит.', 'литров')], max_length=10, verbose_name='единица измерения'),
        ),
    ]
